language: cpp
compiler:
  - clang
dist: trusty
before_install:
 - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
 - sudo apt-get -qq update
 - sudo apt-get install -y libssl-dev libgtest-dev valgrind
 - sudo apt-get install --only-upgrade cmake
 - cmake --version 
 # GTest
 - wget -O gtest.tar.gz https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - tar xf gtest.tar.gz
 - cd googletest-release-1.7.0
 - cmake -DBUILD_SHARED_LIBS=ON .
 - make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - cd ..
 ## Easylogging++
 - wget https://github.com/muflihun/easyloggingpp/archive/develop.zip
 - unzip develop.zip
 - cd easyloggingpp-develop
 - cmake .
 - make
 - sudo make install
 ## Build
 - cd "${TRAVIS_BUILD_DIR}"
 - mkdir build
 - cd build
 - pwd
 - ls -l
 - ls -l ..
 - cmake -Dtest=ON -Dtravis=ON ..
 - make

script: "echo 'echo \"EM+2WPE9fXxrna+Pyb0Ycw==\" | valgrind ./ripe -d --key my_key --iv 313004c475a3986d2034e77542ab1d5b --base64' && valgrind ./ripe-unit-tests --leak-check=full"
branches:
  only:
    - master

